version: '3.7'

networks:
  backend:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: web-dockerfile
    #working_dir: /go/src/music-metadata/
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ".:/app"
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]

  db:
    image: postgres:15.5-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

volumes:
  web:
